### ISSUE TITLE
Getting Started TODO list

### ISSUE THREAD

**Issue by bitfyre** [fizzion/fizzion#1]
- [ ] Define naming conventions
- [ ] How do those map to file setup
- [ ] Break out into npm modules?
- [ ] Buy Fizzion.io
- [ ] Build tools
- [ ] Reusable templates
- [ ] Gitter setup
- [ ] Extension of Atomic CSS, maybe?
  - [ ] Reading
    - [ ] http://benfrain.com/enduring-css-writing-style-sheets-rapidly-changing-long-lived-projects/
    - [ ] http://benfrain.com/oocss-atomic-css-responsive-web-design-anti-pattern/
    - [ ] http://benfrain.com/fun-css-naming-convention-explained/
  - [ ] Watching
    - [ ] https://www.youtube.com/playlist?list=PLJKslvBeWd2YK1R40l3-7KHLQufv5KyBu
- [ ] Visual regression testing
- [ ] Grouping HTML, CSS, & JS together?
- [x] Make Onion logo :)

**Comment by ryanburgess** [comment]
What do you think about having a full style guide with components as well? I feel like a good Node CLI scaffolding tool could be very powerful?

**Comment by bitfyre** [comment]
I was actually thinking something like that could be quite useful

**Comment by ryanburgess** [comment]
Alright cool. I feel like that's a good place to start.
